### ISSUE TITLE
Possible issue with Mosquitto?

### ISSUE THREAD

**Issue by MostHated** [hapu2000/smarthome_public#1]
Hey there,
    I came across this and wanted to try it out but came across an issue. I already had Home Assistant setup on my Pi4, with MariaDB on my NAS and that is all working well. I wanted to spin up MQTT and have a go at that, so I just grabbed the part of the config for it and the files you had in here, but I am getting the following:

```
ERROR: for mosquitto  Cannot start service mosquitto: OCI runtime create failed: container_linu
x.go:370: starting container process caused: exec: "/docker-entrypoint.sh": permission denied:
unknown
```

I noticed the passwd file in conf.d is empty, is that supposed to be that way, or am I to put something in there?

Thanks,
-MH

**Comment by hapu2000** [comment]
Hi, thanks for opening this issue. I'll have a look and keep you updated.
